// Automatically generated by astro-icon
// da39a9defe414d98643d669242b8232e136e711bb6ce66a3bfeb2583d71b2ae0

declare module 'virtual:astro-icon' {
    export type Icon =
        | 'chevron-right'
        | 'close-icon'
        | 'computer-desktop'
        | 'danger'
        | 'github'
        | 'info'
        | 'menu-icon'
        | 'moon'
        | 'sun'
        | 'tip'
        | 'warning'
}
