// Automatically generated by astro-icon
// 2424fd766e341178d4e0d7967eab696fc462617ce664b6843da89bacc1d18e59

declare module 'virtual:astro-icon' {
    export type Icon =
        | 'chevron-right'
        | 'close-icon'
        | 'computer-desktop'
        | 'github'
        | 'menu-icon'
        | 'moon'
        | 'sun'
}
